apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mongo-0
    controller: mongodb-enterprise-operator
    pod-anti-affinity: mongo-0
  name: data-mongo-0-0
  namespace: mongodb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 16G
  storageClassName: kops-ssd-1-17
  volumeMode: Filesystem
