---
apiVersion: mongodb.com/v1
kind: MongoDBMulti
metadata:
  name: multi-replica-set
spec:
  version: 4.4.0-ent
  type: ReplicaSet
  persistent: false
  duplicateServiceObjects: false
  credentials: my-credentials
  security:
    authentication:
      enabled: true
      modes: ["SCRAM"]
  opsManager:
    configMapRef:
      name: my-project
  clusterSpecList:
    clusterSpecs:
      - clusterName: e2e.cluster1.mongokubernetes.com
        members: 1
      - clusterName: e2e.cluster2.mongokubernetes.com
        members: 1
      - clusterName: e2e.cluster3.mongokubernetes.com
        members: 1
