apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-enterprise-operator
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: mongodb-enterprise-operator
      app.kubernetes.io/name: mongodb-enterprise-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/instance: mongodb-enterprise-operator
        app.kubernetes.io/name: mongodb-enterprise-operator
    spec:
      serviceAccountName: mongodb-enterprise-operator-multi-cluster
      containers:
      - args:
        - -watch-resource=mongodbmulti
        - -watch-resource=opsmanagers
        - -cluster-names=e2e.cluster1.mongokubernetes.com,e2e.cluster2.mongokubernetes.com
        command:
        - /usr/local/bin/mongodb-enterprise-operator
        env:
        - name: OPERATOR_ENV
          value: dev
        - name: WATCH_NAMESPACE
          # specify the namespace where the MDB CR is deployed, use "*" for all namespaces.
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: CURRENT_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: IMAGE_PULL_POLICY
          value: Always
        - name: MONGODB_ENTERPRISE_DATABASE_IMAGE
          value: quay.io/mongodb/mongodb-enterprise-database
        - name: INIT_DATABASE_IMAGE_REPOSITORY
          value: quay.io/mongodb/mongodb-enterprise-init-database
        - name: INIT_DATABASE_VERSION
          value: 1.0.4
        - name: DATABASE_VERSION
          value: 2.0.1
        - name: OPS_MANAGER_IMAGE_REPOSITORY
          value: quay.io/mongodb/mongodb-enterprise-ops-manager
        - name: INIT_OPS_MANAGER_IMAGE_REPOSITORY
          value: quay.io/mongodb/mongodb-enterprise-init-ops-manager
        - name: INIT_OPS_MANAGER_VERSION
          value: 1.0.5
        - name: INIT_APPDB_IMAGE_REPOSITORY
          value: quay.io/mongodb/mongodb-enterprise-init-appdb
        - name: INIT_APPDB_VERSION
          value: 1.0.8
        - name: OPS_MANAGER_IMAGE_PULL_POLICY
          value: Always
        - name: AGENT_IMAGE
          value: quay.io/mongodb/mongodb-agent:10.29.0.6830-1
        - name: MONGODB_IMAGE
          value: mongodb-enterprise-appdb-database
        - name: MONGODB_REPO_URL
          value: quay.io/mongodb
        image: 268558157000.dkr.ecr.eu-west-1.amazonaws.com/raj/ubuntu/mongodb-enterprise-operator:latest
        imagePullPolicy: Always
        name: mongodb-enterprise-operator
        volumeMounts:
          - name: kube-config-volume
            mountPath: /etc/config/kubeconfig
        resources:
          limits:
            cpu: 1100m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
      terminationGracePeriodSeconds: 30
      volumes:
        - name: kube-config-volume
          secret:
            secretName: mongodb-enterprise-operator-multi-cluster-kubeconfig
