version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    reviewers:
      - "irajdeep"
      - "mircea-cosbuc"
      - "priyolahiri"
      - "lsierant"
