{{- if not (lookup "cert-manager.io/v1" "Issuer"   .Release.Namespace  "ca-issuer") }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: ca-key-pair
{{end}}
