{{- if not (lookup "v1" "Secret"  .Release.Namespace  "ca-key-pair") }}
apiVersion: v1
kind: Secret
metadata:
  name: ca-key-pair
  namespace: {{ .Release.Namespace }}
data:
  tls.crt:  {{ $.Files.Get "ca_tls.crt" | b64enc}}
  tls.key: {{ $.Files.Get "ca_tls.key" | b64enc}}
{{end}}
