{{range $index, $e := until ( .Values.members | int ) }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $.Values.name }}-{{$index}}
  namespace: {{ $.Release.Namespace }}
spec:
  dnsNames:
  - {{ $.Values.name }}-{{$index}}.{{ $.Values.name }}.{{ $.Release.Namespace }}.svc.{{ $.Values.clusterName }}
  - {{ $.Values.name }}-{{$index}}
  secretName: {{ $.Values.name }}-{{$index}}-abcd
  issuerRef:
    name: ca-issuer
  duration: "240h"
  renewBefore: "120h"
  usages:
    - "server auth"
    - "client auth"
{{end}}
