parameters:
- key: registry
  value: 268558157000.dkr.ecr.us-east-1.amazonaws.com
  description: Development ECR registry

- key: pin_tag_at
  value: 00:00
  description: Pin tags at this time of the day. Midnight by default.

### All the functions in this file are copies of what is in
### .evergreen.yml. If there's any modification on these, it should be also
### modified in there.
functions:
  clone:
  - command: subprocess.exec
    type: setup
    params:
      command: "mkdir -p src/github.com/10gen"
  - command: git.get_project
    type: setup
    params:
      directory: src/github.com/10gen/ops-manager-kubernetes

  setup_preflight:
  - command: subprocess.exec
    type: setup
    params:
      working_dir: src/github.com/10gen/ops-manager-kubernetes
      add_to_path:
        - ${workdir}/bin
      include_expansions_in_env:
      - workdir
      binary: scripts/evergreen/setup_preflight.sh

  preflight_image:
  - command: subprocess.exec
    type: setup
    params:
      command: python3 -m venv --upgrade ./venv
  - command: subprocess.exec
    type: setup
    params:
      working_dir: src/github.com/10gen/ops-manager-kubernetes
      command: ${workdir}/venv/bin/python -m pip install -r requirements.txt --quiet
  - command: subprocess.exec
    type: setup
    params:
      include_expansions_in_env:
      - RED_HAT_TOKEN
      - rh_e2e_cluster_user
      command: "podman login -u=\"${rh_e2e_cluster_user}\" -p=\"${RED_HAT_TOKEN}\" registry.connect.redhat.com"
  - command: subprocess.exec
    params:
      working_dir: src/github.com/10gen/ops-manager-kubernetes
      add_to_path:
      - ${workdir}/bin
      include_expansions_in_env:
      - project_id
      - rh_pyxis
      command: "${workdir}/venv/bin/python scripts/preflight_images.py --image ${image_name}"

  configure_docker_auth:
  - command: subprocess.exec
    type: setup
    params:
      working_dir: src/github.com/10gen/ops-manager-kubernetes
      add_to_path:
        - ${workdir}/bin
      include_expansions_in_env:
      - workdir
      binary: scripts/evergreen/setup_aws.sh
  - command: subprocess.exec
    type: setup
    params:
      working_dir: src/github.com/10gen/ops-manager-kubernetes
      add_to_path:
      - ${workdir}/bin
      include_expansions_in_env:
      - workdir
      - RED_HAT_TOKEN
      env:
        AWS_ACCESS_KEY_ID: ${mms_eng_test_aws_access_key}
        AWS_SECRET_ACCESS_KEY: ${mms_eng_test_aws_secret}
        AWS_DEFAULT_REGION: ${mms_eng_test_aws_region}
      binary: scripts/dev/configure_docker_auth.sh
  - command: subprocess.exec
    type: setup
    params:
      command: "docker login quay.io -u ${quay_prod_username} -p ${quay_prod_robot_token}"

  configure_rh_docker_auth:
  - command: subprocess.exec
    type: setup
    params:
      # Note: we add || true to keep going if RH connect is failing for some maintenance/temporary error
      # We need to wrap the command in `sh -c 'command'` otherwise we can't use || operator
      command: "sh -c 'docker login scan.connect.redhat.com -u unused -p ${project_id} || true'"


  build_and_push_appdb_database:
    - command: subprocess.exec
      params:
        include_expansions_in_env:
          - workdir
        working_dir: src/github.com/10gen/ops-manager-kubernetes/docker/mongodb-enterprise-appdb-database
        binary: ./build_and_push_appdb_database_images.sh
        add_to_path:
          - ${workdir}/bin
          - ${workdir}
        env:
          AWS_ACCESS_KEY_ID: ${mms_eng_test_aws_access_key}
          AWS_SECRET_ACCESS_KEY: ${mms_eng_test_aws_secret}
          AWS_DEFAULT_REGION: ${mms_eng_test_aws_region}


  pipeline:
  - command: subprocess.exec
    type: setup
    params:
      command: /opt/python/3.9/bin/python3 -m venv --upgrade-deps ./venv
  - command: subprocess.exec
    type: setup
    params:
      working_dir: src/github.com/10gen/ops-manager-kubernetes
      command: ${workdir}/venv/bin/python -m pip install -r requirements.txt --quiet --no-warn-script-location
  - command: subprocess.exec
    type: setup
    params:
      working_dir: src/github.com/10gen/ops-manager-kubernetes
      env:
        AWS_ACCESS_KEY_ID: ${mms_eng_test_aws_access_key}
        AWS_SECRET_ACCESS_KEY: ${mms_eng_test_aws_secret}
        AWS_DEFAULT_REGION: ${mms_eng_test_aws_region}
      include_expansions_in_env:
      - version_id
      - registry
      - distro
      - include_tags
      - skip_tags
      - test_suffix
      - om_version
      - created_at
      - pin_tag_at
      add_to_path:
      - ${workdir}/bin
      command: "${workdir}/venv/bin/python pipeline.py --include ${image_name}"

tasks:
- name: preflight_images
  commands:
  - func: clone
  - func: setup_preflight
  - func: preflight_image
    vars:
      image_name: operator
      project_id: ${rhc_operator_pid}
  - func: preflight_image
    vars:
      image_name: ops-manager
      project_id: ${rhc_om_pid}
  - func: preflight_image
    vars:
      image_name: init-appdb
      project_id: ${rhc_init_appdb_pid}
  - func: preflight_image
    vars:
      image_name: init-database
      project_id: ${rhc_init_database_pid}
  - func: preflight_image
    vars:
      image_name: init-ops-manager
      project_id: ${rhc_init_om_pid}
  - func: preflight_image
    vars:
      image_name: appdb
      project_id: ${rhc_appdb_pid}
  - func: preflight_image
    vars:
      image_name: database
      project_id: ${rhc_database_pid}
  - func: preflight_image
    vars:
      image_name: mongodb-agent
      project_id: ${rhc_agent_pid}

- name: periodic_build_operator
  commands:
  - func: clone
  - func: configure_docker_auth
  - func: configure_rh_docker_auth
    vars:
      project_id: ${rhc_operator_pid}
  - func: pipeline
    vars:
      image_name: operator-daily

- name: periodic_build_init_appdb
  commands:
  - func: clone
  - func: configure_docker_auth
  - func: configure_rh_docker_auth
    vars:
      project_id: ${rhc_init_appdb_pid}
  - func: pipeline
    vars:
      image_name: init-appdb-daily

- name: periodic_build_init_database
  commands:
  - func: clone
  - func: configure_docker_auth
  - func: configure_rh_docker_auth
    vars:
      project_id: ${rhc_init_database_pid}
  - func: pipeline
    vars:
      image_name: init-database-daily

- name: periodic_build_init_opsmanager
  commands:
  - func: clone
  - func: configure_docker_auth
  - func: configure_rh_docker_auth
    vars:
      project_id: ${rhc_init_om_pid}
  - func: pipeline
    vars:
      image_name: init-ops-manager-daily

- name: periodic_build_appdb
  commands:
  - func: clone
  - func: configure_docker_auth
  - func: configure_rh_docker_auth
    vars:
      project_id: ${rhc_appdb_pid}
  - func: pipeline
    vars:
      image_name: appdb-daily

- name: periodic_build_database
  commands:
  - func: clone
  - func: configure_docker_auth
  - func: configure_rh_docker_auth
    vars:
      project_id: ${rhc_database_pid}
  - func: pipeline
    vars:
      image_name: database-daily

- name: periodic_build_ops_manager_4_4_0
  commands:
  - func: clone
  - func: configure_docker_auth
  - func: configure_rh_docker_auth
    vars:
      project_id: ${rhc_om_pid}
  - func: pipeline
    vars:
      image_name: ops-manager-4-4-0-daily

- name: periodic_build_ops_manager_4_4_10
  commands:
  - func: clone
  - func: configure_docker_auth
  - func: configure_rh_docker_auth
    vars:
      project_id: ${rhc_om_pid}
  - func: pipeline
    vars:
      image_name: ops-manager-4-4-10-daily

- name: periodic_build_ops_manager_4_4_20
  commands:
  - func: clone
  - func: configure_docker_auth
  - func: configure_rh_docker_auth
    vars:
      project_id: ${rhc_om_pid}
  - func: pipeline
    vars:
      image_name: ops-manager-4-4-20-daily


- name: periodic_build_ops_manager_5
  commands:
  - func: clone
  - func: configure_docker_auth
  - func: configure_rh_docker_auth
    vars:
      project_id: ${rhc_om_pid}
  - func: pipeline
    vars:
      image_name: ops-manager-5-daily

- name: periodic_build_ops_manager_6
  commands:
  - func: clone
  - func: configure_docker_auth
  - func: configure_rh_docker_auth
    vars:
      project_id: ${rhc_om_pid}
  - func: pipeline
    vars:
      image_name: ops-manager-6-daily

- name: periodic_build_agent
  commands:
    - func: clone
    - func: configure_docker_auth
    - func: configure_rh_docker_auth
      vars:
        project_id: ${rhc_agent_pid}
    - func: pipeline
      vars:
        image_name: mongodb-agent-daily

- name: periodic_build_appdb_database
  commands:
    - func: clone
    - func: configure_docker_auth
    - func: configure_rh_docker_auth
      vars:
        project_id: ${rhc_appdb_database_pid}
    - func: build_and_push_appdb_database

task_groups:
  - name: periodic_build_task_group
    max_hosts: 5
    tasks:
    - periodic_build_operator
    - periodic_build_init_appdb
    - periodic_build_init_database
    - periodic_build_init_opsmanager
    - periodic_build_ops_manager_4_4_0
    - periodic_build_ops_manager_4_4_10
    - periodic_build_ops_manager_4_4_20
    - periodic_build_ops_manager_5
    - periodic_build_ops_manager_6
    - periodic_build_appdb
    - periodic_build_database
    - periodic_build_agent
    - periodic_build_appdb_database

  - name: preflight_images_task_group
    tasks:
    - preflight_images

buildvariants:
- name: periodic_build
  display_name: periodic_build
  run_on:
  - ubuntu1804-small
  tasks:
    - name: periodic_build_task_group

- name: preflight_images
  display_name: preflight_images
  depends_on:
    # We have to add every task in the periodic build variant here
    # because otherwise evergreen moves on to the preflight task after
    # a single task in the referenced task group succeeds.
    - name: periodic_build_operator
      variant: periodic_build
    - name: periodic_build_init_appdb
      variant: periodic_build
    - name: periodic_build_init_database
      variant: periodic_build
    - name: periodic_build_init_opsmanager
      variant: periodic_build
    - name: periodic_build_ops_manager_4_4_0
      variant: periodic_build
    - name: periodic_build_ops_manager_4_4_10
      variant: periodic_build
    - name: periodic_build_ops_manager_4_4_20
      variant: periodic_build
    - name: periodic_build_ops_manager_5
      variant: periodic_build
    - name: periodic_build_ops_manager_6
      variant: periodic_build
    - name: periodic_build_appdb
      variant: periodic_build
    - name: periodic_build_database
      variant: periodic_build
    - name: periodic_build_agent
      variant: periodic_build
    - name: periodic_build_appdb_database
      variant: periodic_build
  run_on:
  - rhel90-small
  tasks:
    - name: preflight_images_task_group
