# MongoDB Kubernetes Operator CI Configuration
# This file now uses a modular structure for better maintainability
# All configuration has been organized into logical, focused files

include:
  - filename: .evergreen/main.yml


tasks:
  # add a noop task because if the only task in a variant is git_tag_only: true Evergreen doesn't start it at all
  - name: noop
    commands:
      - command: shell.exec
        params:
          shell: bash
          script: echo "this is the noop task"

buildvariants:
  # This variant is run when a new tag is out similar to github actions.
  - name: noop
    display_name: Noop
    run_on:
      - ubuntu2204-small
    tasks:
      - name: noop
