# Evergreen configuration for MongoDB Cloud, Atlas and OpsManager
stepback: true

variables:
  ops_manager_version: "3.7.0"

functions:
  "setup": &setup
    command: git.get_project
    type: system
    params:
      directory: ops-manager-kubernetes



tasks:

- name: SETUP
  tags: ["setup"]
  commands:
    - func: "setup"


buildvariants:

- name: one_teo
  display_name: 1.
  run_on:
    - rhel70-small
  batchtime: 1440 # 1 day
  stepback: false
  tasks:
    - ".setup"
