include:
  - filename: .evergreen-functions.yml
  - filename: .evergreen-tasks.yml

parameters:
  - key: pin_tag_at
    value: 00:00
    description: Pin tags at this time of the day. Midnight by default.

tasks:
  - name: periodic_build_operator
    commands:
      - func: clone
      - func: setup_docker_sbom
      - func: setup_aws
      - func: configure_docker_auth
      - func: quay_login
      - func: pipeline
        vars:
          image_name: operator-daily

  - name: periodic_build_init_appdb
    commands:
      - func: clone
      - func: setup_docker_sbom
      - func: setup_aws
      - func: configure_docker_auth
      - func: quay_login
      - func: pipeline
        vars:
          image_name: init-appdb-daily

  - name: periodic_build_init_database
    commands:
      - func: clone
      - func: setup_docker_sbom
      - func: setup_aws
      - func: configure_docker_auth
      - func: quay_login
      - func: pipeline
        vars:
          image_name: init-database-daily

  - name: periodic_build_init_opsmanager
    commands:
      - func: clone
      - func: setup_docker_sbom
      - func: setup_aws
      - func: configure_docker_auth
      - func: quay_login
      - func: pipeline
        vars:
          image_name: init-ops-manager-daily

  - name: periodic_build_database
    commands:
      - func: clone
      - func: setup_docker_sbom
      - func: setup_aws
      - func: configure_docker_auth
      - func: quay_login
      - func: pipeline
        vars:
          image_name: database-daily

  - name: periodic_build_sbom_cli
    commands:
      - func: clone
      - func: setup_docker_sbom
      - func: setup_aws
      - func: configure_docker_auth
      - func: quay_login
      - func: pipeline
        vars:
          image_name: cli

  - name: periodic_build_ops_manager_6
    commands:
      - func: clone
      - func: setup_docker_sbom
      - func: setup_aws
      - func: configure_docker_auth
      - func: quay_login
      - func: pipeline
        vars:
          image_name: ops-manager-6-daily

  - name: periodic_build_ops_manager_7
    commands:
      - func: clone
      - func: setup_docker_sbom
      - func: setup_aws
      - func: configure_docker_auth
      - func: quay_login
      - func: pipeline
        vars:
          image_name: ops-manager-7-daily

  - name: periodic_build_ops_manager_8
    commands:
      - func: clone
      - func: setup_docker_sbom
      - func: setup_aws
      - func: configure_docker_auth
      - func: quay_login
      - func: pipeline
        vars:
          image_name: ops-manager-8-daily

  - name: periodic_build_agent
    exec_timeout_secs: 43200
    commands:
      - func: clone
      - func: setup_docker_sbom
      - func: setup_aws
      - func: configure_docker_auth
      - func: quay_login
      - func: enable_QEMU
      - func: pipeline
        vars:
          image_name: mongodb-agent-daily

  - name: periodic_build_community_operator
    commands:
      - func: clone
      - func: setup_docker_sbom
      - func: setup_aws
      - func: configure_docker_auth
      - func: quay_login
      - func: enable_QEMU
      - func: pipeline
        vars:
          image_name: mongodb-kubernetes-operator-daily

  - name: periodic_build_readiness_probe
    commands:
      - func: clone
      - func: setup_docker_sbom
      - func: setup_aws
      - func: configure_docker_auth
      - func: quay_login
      - func: pipeline
        vars:
          image_name: mongodb-kubernetes-readinessprobe-daily

  - name: periodic_build_version_upgrade_post_start_hook
    commands:
      - func: clone
      - func: setup_docker_sbom
      - func: setup_aws
      - func: configure_docker_auth
      - func: quay_login
      - func: pipeline
        vars:
          image_name: mongodb-kubernetes-operator-version-upgrade-post-start-hook-daily

  - name: periodic_build_appdb_database
    commands:
      - func: clone
      - func: setup_docker_sbom
      - func: setup_aws
      - func: configure_docker_auth
      - func: quay_login
      - func: build_and_push_appdb_database

  - name: prepare_and_upload_openshift_bundles
    commands:
      - func: clone
      - func: setup_aws
      - func: configure_docker_auth
      - func: quay_login
      - func: setup_prepare_openshift_bundles
      - func: prepare_openshift_bundles
      - func: update_evergreen_expansions
      - func: upload_openshift_bundle
        vars:
          # mongoDbOperator expansion is added in update_evergreen_expansions func from release.json
          bundle_file_name: "operator-community-${mongodbOperator}.tgz"
      - func: upload_openshift_bundle
        vars:
          bundle_file_name: "operator-certified-${mongodbOperator}.tgz"

  - name: run_conditionally_prepare_and_upload_openshift_bundles
    commands:
      - func: clone
      - func: run_task_conditionally
        vars:
          condition_script: scripts/evergreen/should_prepare_openshift_bundles.sh
          variant: prepare_openshift_bundles
          task: prepare_and_upload_openshift_bundles

  - name: teardowns
    commands:
      - func: clone
      - func: teardown_cloud_qa_all
      - func: cleanup_aws

task_groups:
  - name: periodic_build_task_group
    max_hosts: -1
    tasks:
      - periodic_build_operator
      - periodic_build_readiness_probe
      - periodic_build_version_upgrade_post_start_hook
      - periodic_build_init_appdb
      - periodic_build_init_database
      - periodic_build_init_opsmanager
      - periodic_build_ops_manager_6
      - periodic_build_ops_manager_7
      - periodic_build_ops_manager_8
      - periodic_build_database
      - periodic_build_agent
      - periodic_build_community_operator
      - periodic_build_appdb_database
      - periodic_build_sbom_cli

  - name: preflight_images_task_group
    max_hosts: -1
    tasks:
      - preflight_images
      - preflight_official_database_image
      - preflight_mongodb_agent_image
      - preflight_ops_manager

  - name: periodic_teardown_task_group
    tasks:
      - teardowns

buildvariants:
  - name: periodic_teardown
    display_name: periodic_teardown
    run_on:
      - ubuntu2204-small
    tasks:
      - name: periodic_teardown_task_group

  - name: periodic_build
    display_name: periodic_build
    run_on:
      - ubuntu1804-large
    tasks:
      - name: periodic_build_task_group

  - name: preflight_images
    display_name: preflight_images
    depends_on:
      # We have to add every task in the periodic build variant here
      # because otherwise evergreen moves on to the preflight task after
      # a single task in the referenced task group succeeds.
      - name: periodic_build_operator
        variant: periodic_build
      - name: periodic_build_init_appdb
        variant: periodic_build
      - name: periodic_build_init_database
        variant: periodic_build
      - name: periodic_build_init_opsmanager
        variant: periodic_build
      - name: periodic_build_ops_manager_6
        variant: periodic_build
      - name: periodic_build_ops_manager_7
        variant: periodic_build
      - name: periodic_build_ops_manager_8
        variant: periodic_build
      - name: periodic_build_database
        variant: periodic_build
      - name: periodic_build_agent
        variant: periodic_build
      - name: periodic_build_appdb_database
        variant: periodic_build
    run_on:
      - rhel90-large
    expansions:
      preflight_submit: true
    tasks:
      - name: preflight_images_task_group

  - name: prepare_openshift_bundles
    display_name: prepare_openshift_bundles
    depends_on:
      # We have to add every task in the periodic build variant here
      # because otherwise evergreen moves on to the preflight task after
      # a single task in the referenced task group succeeds.
      - name: periodic_build_operator
        variant: periodic_build
      - name: periodic_build_readiness_probe
        variant: periodic_build
      - name: periodic_build_version_upgrade_post_start_hook
        variant: periodic_build
      - name: periodic_build_init_appdb
        variant: periodic_build
      - name: periodic_build_init_database
        variant: periodic_build
      - name: periodic_build_init_opsmanager
        variant: periodic_build
      - name: periodic_build_ops_manager_6
        variant: periodic_build
      - name: periodic_build_ops_manager_7
        variant: periodic_build
      - name: periodic_build_ops_manager_8
        variant: periodic_build
      - name: periodic_build_database
        variant: periodic_build
      - name: periodic_build_agent
        variant: periodic_build
      - name: periodic_build_appdb_database
        variant: periodic_build
    run_on:
      - ubuntu2204-large
    tasks:
      - name: run_conditionally_prepare_and_upload_openshift_bundles
