---
#########################
#########################
## Golang Linter rules ##
#########################
#########################

# configure golangci-lint
# see https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
issues:
  exclude-rules:
    - path: _test\.go
      linters:
      - dupl
      - gosec
      - goconst
linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - stylecheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - rowserrcheck
    - gosec
    - unconvert
    - goimports
    - gofmt
    - dupl
    - goconst
    - gofumpt

run:
  modules-download-mode: mod
  # timeout for analysis, e.g., 30s, 5m, default is 1m
  timeout: 5m
  # default concurrency is an available CPU number
  concurrency: 4

linters-settings:
  stylecheck:
    # STxxxx checks in https://staticcheck.io/docs/configuration/options/#checks
    # Default: ["*"]
    checks: ["all", "-ST1000", "-ST1003", "-ST1020", "-ST1021", "-ST1022", "-ST1023"]

  gofumpt:
    # Module path which contains the source code being formatted.
    # Default: ""
    module-path: github.com/10gen/ops-manager-kubernetes