---
apiVersion: v1
kind: Namespace
metadata:
  name: mongodb

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: om-operator
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - mongodb.com
  resources:
  - "*"
  verbs:
  - "*"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: om-operator
  namespace: mongodb

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: om-operator
  namespace: mongodb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: om-operator
subjects:
- kind: ServiceAccount
  name: om-operator
  namespace: mongodb

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: om-operator
  namespace: mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: om-operator
    spec:
      serviceAccountName: om-operator
      containers:
      - name: om-operator
        image: 268558157000.dkr.ecr.us-east-1.amazonaws.com/dev/om-operator
        env:
        - name: OM_OPERATOR_ENV
          value: "dev"
