---
apiVersion: v1
kind: Namespace
metadata:
  name: mongodb


---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: om-operator
  namespace: mongodb
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs: ["*"]
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - mongodb.com
  resources:
  - "*"
  verbs:
  - "*"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: om-operator
  namespace: mongodb

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: om-operator
  namespace: mongodb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: om-operator
subjects:
- kind: ServiceAccount
  name: om-operator
  namespace: mongodb

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: om-operator
  namespace: mongodb


---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: om-operator
  namespace: mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: om-operator
    spec:
      serviceAccountName: om-operator
      containers:
      - name: om-operator
        image: om-operator
        imagePullPolicy: Never
        env:
        - name: OM_OPERATOR_ENV
          value: "local"
