kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: om-operator
rules:
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - mongodb.com
  resources:
  - "*"
  verbs:
  - "*"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: om-operator
  namespace: default

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: om-operator
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: om-operator
subjects:
- kind: ServiceAccount
  name: om-operator
  namespace: default

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: om-operator
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: om-operator
    spec:
      serviceAccountName: om-operator
      containers:
      - name: om-operator
        image: om-operator:0.1
        envFrom:
        - configMapRef:
            name: ops-manager-config
