---
apiVersion: v1
kind: Service
metadata:
  name: alpha-service
  labels:
    app: alpha-service
spec:
  ports:
  - port: 27017
    name: liffey
  clusterIP: None
  selector:
    app: alpha-service

---
apiVersion: mongodb.com/v1alpha1
kind: MongoDbReplicaSet
metadata:
  name: liffey
spec:
  members: 3
  hostname_prefix: liffey
  mongodb_version: 3.6.3
  name: liffey
  service: alpha-service
