---
kind: {{ if .Values.operator.watchNamespace }} {{ if (eq .Values.operator.watchNamespace "*") }} ClusterRole {{ else }} Role {{ end }} {{ else }} Role {{ end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.operator.name }}
{{ if .Values.namespace }}
  namespace: {{ .Values.namespace }}
{{ end }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs: ["*"]
- apiGroups:
  - mongodb.com
  resources:
  - "*"
  verbs:
  - "*"

---
kind: {{ if .Values.operator.watchNamespace }} {{ if (eq .Values.operator.watchNamespace "*") }} ClusterRoleBinding {{ else }} RoleBinding {{ end }} {{ else }} RoleBinding {{ end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.operator.name }}
{{ if .Values.namespace }}
  namespace: {{ .Values.namespace }}
{{ end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ if .Values.operator.watchNamespace }} {{ if (eq .Values.operator.watchNamespace "*") }} ClusterRole {{ else }} Role {{ end }} {{ else }} Role {{ end }}
  name: {{ .Values.operator.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.operator.name }}
{{ if .Values.namespace }}
  namespace: {{ .Values.namespace }}
{{ end }}

# This ClusterRole is needed if the user wants to use the Kubernetes CA
# infrastructure to generate certificates.
# TODO: Set the right resources and verbs in this yaml doc.
{{ if .Values.needsCAInfrastructure }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.operator.name }}-{{ .Values.namespace }}-certs
rules:
- apiGroups:
  - certificates.k8s.io
  resources: ["*"]
  verbs: ["*"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.operator.name }}-{{ .Values.namespace }}-certs-binding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.operator.name }}-{{ .Values.namespace }}-certs
subjects:
- kind: ServiceAccount
  name: {{ .Values.operator.name }}
  namespace: {{ .Values.namespace }}

{{ end }}
