nameReference:
  - kind: Service
    version: v1
    fieldSpecs:
      # this is for operator-sdk to glue service, webhook definitions and put it in CSV
      - kind: ValidatingWebhookConfiguration
        group: admissionregistration.k8s.io
        path: webhooks/clientConfig/service/name
