apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: appdb
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - patch
