# permissions for end users to view mongdbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongodb-viewer-role
rules:
- apiGroups:
  - mongodb.com
  resources:
  - mongodb
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mongodb.com
  resources:
  - mongodb/status
  verbs:
  - get
