---
apiVersion: v1
kind: Service
metadata:
  name: ops-manager
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.opsManager.name }}
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.opsManager.name }}
  name: opsmanager-svc-external
  namespace: {{ .Values.namespace }}
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30039
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Values.opsManager.name }}
  sessionAffinity: None
  type: NodePort

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ .Values.opsManager.name }}
  name: {{ .Values.opsManager.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  serviceName: ops-manager
  selector:
    matchLabels:
      app: {{ .Values.opsManager.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.opsManager.name }}
    spec:
      containers:
      - name: {{ .Values.opsManager.name }}
        image: {{ .Values.registry.repository }}/mongodb-enterprise-ops-manager:{{ .Values.opsManager.version }}
        imagePullPolicy: {{ .Values.registry.pullPolicy }}
        readinessProbe:
          httpGet:
            port: 8080
            path: /
          initialDelaySeconds: 30
          timeoutSeconds: 1
        env:
        - name: OM_HOST
          value: {{ .Values.opsManager.host }}
        resources:
          requests:
            memory: "6Gi"
      imagePullSecrets: 
      - name: {{ .Values.registry.imagePullSecret }}
