---
apiVersion: v1
kind: Service
metadata:
  name: ops-manager
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.opsManager.name }}
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.opsManager.name }}
  name: opsmanager-svc-external
  namespace: {{ .Values.namespace }}
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: {{ .Values.opsManager.nodePort }}
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Values.opsManager.name }}
  sessionAffinity: None
  type: NodePort

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ .Values.opsManager.name }}
  name: {{ .Values.opsManager.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  serviceName: ops-manager
  selector:
    matchLabels:
      app: {{ .Values.opsManager.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.opsManager.name }}
    spec:
      containers:
      - name: {{ .Values.opsManager.name }}
        image: {{ .Values.registry.repository }}/mongodb-enterprise-ops-manager:{{ .Values.opsManager.version }}
        imagePullPolicy: {{ .Values.registry.pullPolicy }}
        readinessProbe:
          httpGet:
            port: 8080
            path: /
          initialDelaySeconds: 30
          timeoutSeconds: 1
        env:
        - name: OM_HOST
          value: {{ .Values.opsManager.host }}
        volumeMounts:
        - name: mongodb-mms-data
          mountPath: /data
        - name: mongodb-mms-config
          mountPath: /etc/mongodb-mms
        - name: mongodb-mms-logs
          mountPath: /opt/mongodb/mms/logs
        - name: mongodb-mms-env
          mountPath: /opt/mongodb/mms/env
        resources:
          requests:
            memory: "5Gi"
      imagePullSecrets:
      - name: {{ .Values.registry.imagePullSecret }}
#      TODO the affinity rule for some reasons doesn't work for kops cluster:
#        0/5 nodes are available: 1 Insufficient memory, 1 node(s) didn''t
#        match pod affinity/anti-affinity, 1 node(s) didn''t match pod anti-affinity
#        rules, 3 node(s) had no available volume zone.
#      affinity:
#        podAntiAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#          - labelSelector:
#              matchExpressions:
#              - key: app
#                operator: In
#                values:
#                - mongodb-enterprise-ops-manager
#            topologyKey: "kubernetes.io/hostname"
#              namespaces:
#              - operator-testing-40-first
#              - operator-testing-40-current
  volumeClaimTemplates:
  - metadata:
      name: mongodb-mms-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: mongodb-mms-logs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
  - metadata:
      name: mongodb-mms-config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: mongodb-mms-env
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
