---
- hosts: masters
  gather_facts: no

  tasks:

  - name: configure admin with cluster-admin role
    run_once: true
    shell: |
      oc login -u system:admin  # login as system:admin (needs to be done at the master)
      oc adm policy add-cluster-role-to-user cluster-admin admin

      oc login -u system:christian
      oc adm policy add-cluster-role-to-user cluster-admin admin

      oc login -u system:rodrigo
      oc adm policy add-cluster-role-to-user cluster-admin admin

      oc login -u system:anton
      oc adm policy add-cluster-role-to-user cluster-admin admin

  - name: configure long lasting tokens
    run_once: true
    lineinfile:
      path: /etc/origin/master/master-config.yaml
      regexp: 'accessTokenMaxAgeSeconds: \d+$'
      line: '    accessTokenMaxAgeSeconds: 8640000'

  - name: restart openshift API
    run_once: true
    shell: /usr/local/bin/master-restart api
