---
- hosts: nodes
  gather_facts: no

  tasks:

  - name: install network manager
    yum: state=latest name={{ item }}
    with_items:
    - NetworkManager
    tags: ['nodes']

  - name: enable network-manager
    shell: systemctl enable NetworkManager && systemctl start NetworkManager
    tags: ['nodes']

  - name: mount volume
    shell: |
      mkdir -p /var/lib/docker
      mkfs -t xfs /dev/xvdb
      echo "/dev/xvdb       /var/lib/docker   xfs    defaults,nofail 0       2" >> /etc/fstab
      mount -a

  - name: downgrade to a sane docker version
    yum: allow_downgrade=yes state=installed name=docker-1.13.1-75.git8633870.el7.centos
    tags: ['nodes']

  - name: start docker
    shell: |
      service docker start
      systemctl enable docker

- hosts: control
  gather_facts: no

  tasks:
  - name: install dependencies
    yum: state=latest name={{ item }}
    with_items:
    - "epel-release"
    - "git"
    - "screen"
    become: yes
    become_user: root

  - name: install python36
    yum: state=installed name=python36
    become: yes
    become_user: root

  - name: install pip
    shell: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python36 get-pip.py || true
    become: yes
    become_user: root

  - name: install ansible
    shell: python36 -m pip install ansible==2.6.5 --user

  - name: ssh config
    shell: |
      echo "Host *.compute-1.amazonaws.com" > ~/.ssh/config
      echo "  StrictHostKeyChecking no"     >> ~/.ssh/config
      chmod g-w ~/.ssh/config

  - name: clone openshift-ansible
    git:
      repo: https://github.com/openshift/openshift-ansible.git
      dest: ~/openshift-ansible
      version: release-3.11

  - name: copy inventory files
    copy:
      src: hosts.certification
      dest: ~/hosts.certification

  - name: copy exports file
    copy:
      src: exports.do
      dest: ~/exports.do
