---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager-localmode
spec:
  replicas: 1
  version: 4.4.14
  adminCredentials: ops-manager-admin-secret

  # Local Mode must be configured so Ops Manger does not download any binaries from
  # the internet. Only the binaries present will be available for the agents.
  configuration:
    automation.versions.source: local

  statefulSet:
    spec:
      template:
        spec:
          volumes:
            - name: mongodb-versions
              persistentVolumeClaim:
                claimName: mongodb-versions-claim
          containers:
            - name: mongodb-ops-manager
              volumeMounts:
                - name: mongodb-versions
                  mountPath: /mongodb-ops-manager/mongodb-releases

          initContainers:
          - name: mongod-binaries-rhel70-init-container
            image: quay.io/mongodb/mongodb-enterprise-init-mongod-rhel80:4.4.4
            command:
            - cp
            - -a
            - /binaries/.
            - /mongodb-ops-manager/mongodb-releases/
            volumeMounts:
             - name: mongodb-versions
               mountPath: /mongodb-ops-manager/mongodb-releases

  backup:
    enabled: false

  applicationDatabase:
    version: "4.4.1"
    members: 3

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-versions-claim
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

