{{ if .Values.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ops-manager-cleaner
  namespace: {{ .Values.namespace }}

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ops-manager-cleaner
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: ops-manager-cleaner
  namespace: {{ .Values.namespace }}

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cluster-cleaner-ops-manager
  namespace: {{ .Values.namespace }}
spec:
  # Run at 3:00 am every day.
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ops-manager-cleaner
          restartPolicy: Never

          containers:
          - name: cluster-cleaner
            image: 268558157000.dkr.ecr.us-east-1.amazonaws.com/dev/cluster-cleaner:{{ .Values.cleanerVersion }}
            imagePullPolicy: Always
            command: ["./clean-ops-manager.sh"]
            env:
            - name: OM_NAMESPACE
              value: {{ .Values.namespace }}
{{ end }}
