{{- range .Values.users }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.name }}-{{ .username }}-secret
  namespace: {{ $.Release.Namespace }}
type: Opaque
stringData:
  password: {{ .password | quote}}
{{- end }}