apiVersion: v2
name: mongodb-enterprise-operator
description: MongoDB Kubernetes Enterprise Operator
version: 1.14.0
kubeVersion: '>=1.16-0'
keywords:
- mongodb
- database
- nosql
home: https://github.com/mongodb/mongodb-enterprise-kubernetes
maintainers:
- name: Cloud Team
