# grant all permissions in all namespaces to the tests
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-tests-service-account
  namespace: {{ .Values.namespace }}

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operator-tests-role-binding-{{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: operator-tests-service-account
  namespace: {{ .Values.namespace }}

---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb-enterprise-operator-tests
  namespace: {{ .Values.namespace }}
  labels:
    role: operator-tests
spec:
  serviceAccountName: operator-tests-service-account
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
  containers:
  - name: mongodb-enterprise-operator-tests
    env:
    - name: OM_HOST
      value: {{ .Values.baseUrl }}
    - name: OM_API_KEY
      value: {{ .Values.apiKey }}
    - name: OM_USER
      value: {{ .Values.apiUser }}
    - name: PROJECT_NAMESPACE
      value: {{ .Values.namespace }}
    # We can pass additional options to pytest. For instance -s
    - name: PYTEST_ADDOPTS
      value: {{ .Values.pytest.addopts }}
    - name: PYTHONUNBUFFERED
      value: 'true'
    image: {{ .Values.repo }}/mongodb-enterprise-tests:{{ .Values.tag }}
    command: ["pytest"]
    # -s  -- disable stdout capture: should be added to `PYTEST_ADDOPTS` if needed
    # -x  -- stop after first failure
    # -v  -- increase verbosity
    args: ["-v", "-x", "{{ .Values.testPath }}"]
    imagePullPolicy: Always
