# grant all permissions in all namespaces to the tests
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-tests-service-account
  namespace: {{ .Values.namespace }}

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operator-tests-role-binding-{{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: operator-tests-service-account
  namespace: {{ .Values.namespace }}

---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb-enterprise-operator-tests
  namespace: {{ .Values.namespace }}
  labels:
    role: operator-tests
spec:
  serviceAccountName: operator-tests-service-account
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
  containers:
  - name: mongodb-enterprise-operator-tests
    env:
    - name: OM_HOST
      value: {{ .Values.baseUrl }}
    - name: OM_API_KEY
      value: {{ .Values.apiKey }}
    - name: OM_USER
      value: {{ .Values.apiUser }}
    - name: PROJECT_NAMESPACE
      value: {{ .Values.namespace }}
    image: {{ .Values.repo }}/mongodb-enterprise-tests:{{ .Values.tag }}
    command: ["pytest"]
    # -x is used to stop after the first failure, -s disables output capturing to see results of 'print()'
    args: ["-v", "-x", "-s", "{{ .Values.testPath }}"]
    imagePullPolicy: Always
