---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-enterprise-ops-manager
  name: ops-manager-internal
spec:
  selector:
    app: mongodb-enterprise-ops-manager
  ports:
  - protocol: TCP
    port: 8080

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongodb-enterprise-ops-manager
  name: mongodb-enterprise-ops-manager
spec:
  replicas: 1
  serviceName: ops-manager
  selector:
    matchLabels:
      app: mongodb-enterprise-ops-manager
  template:
    metadata:
      labels:
        app: mongodb-enterprise-ops-manager
    spec:
      containers:
      - name: mongodb-enterprise-ops-manager
        image: 268558157000.dkr.ecr.us-east-1.amazonaws.com/dev/mongodb-enterprise-ops-manager:4.0.5.50245.20181031T0042Z-1_test
        imagePullPolicy: Always
        env:
        - name: OM_HOST
          value: ops-manager-internal.operator-testing.svc.cluster.local
        volumeMounts:
        - name: mongodb-mms-data
          mountPath: /data
        - name: mongodb-mms-config
          mountPath: /etc/mongodb-mms
        - name: mongodb-mms-logs
          mountPath: /opt/mongodb/mms/logs
        - name: mongodb-mms-env
          mountPath: /opt/mongodb/mms/env
        resources:
          requests:
            memory: "4Gi"
        readinessProbe:
          httpGet:
            port: 8080
            path: /
          initialDelaySeconds: 30
          timeoutSeconds: 1

  volumeClaimTemplates:
  - metadata:
      name: mongodb-mms-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
  - metadata:
      name: mongodb-mms-logs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
  - metadata:
      name: mongodb-mms-config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: mongodb-mms-env
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
