namespace: ${PROJECT_NAMESPACE}
registry:
  repository: 268558157000.dkr.ecr.us-east-1.amazonaws.com/dev
  pullPolicy: Always
  imagePullSecrets:
operator:
  name: mongodb-enterprise-operator
  version: ${REVISION}
  env: dev # keep prod unless you want more debugging (e.g. failing tests)

opsmanager:
  name: mongodb-enterprise-ops-manager
  version: 4.0.2.50187.20180905T1427Z-1
  pullPolicy: IfNotPresent


apiKey: omApiKey
orgId: ""
projectId: omProjectId
tag:
taskName: ${TASK_NAME}

pytest:
  addopts: ""
