apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
spec:
  version: 8.0.8
  adminCredentials: ops-manager-admin
  configuration:
    mms.fromEmailAddr: admin@thecompany.com
  externalConnectivity:
    type: LoadBalancer
  applicationDatabase:
    members: 3
    version: 8.0.8
