namespace: ${PROJECT_NAMESPACE}
registry:
  pullPolicy: Always

managedSecurityContext: false

apiKey: omApiKey
orgId: ""
projectId: omProjectId
tag:
taskName: ${TASK_NAME}

pytest:
  addopts: "-s"

aws:
  accessKey: "none"
  secretAccessKey: "none"


skipExecution: 'false'

# Set this when the ECR registry is not accessible from the testing cluster.
# A Secret with type kubernetes.io/dockerconfigjson needs to exist.
imagePullSecrets:

# Set this to "true" to configure the test pod for running a multi cluster test.
multiCluster: ""
