apiVersion: v1
kind: Pod
metadata:
  name: builder-pod-{{ .Values.podName }}
  labels:
    podbuilderid: {{ .Values.label }}
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v0.15.0
      args: ["--dockerfile=Dockerfile",
            {{- range .Values.buildArgs }}
             "--build-arg={{ . }}",
             {{- end }}
             "--destination={{ .Values.destination }}",
             "--context={{ .Values.context }}",
             "--cache={{ .Values.cache }}",
             "--cache-repo={{ .Values.cacheRepo }}"]
      volumeMounts:
        - name: aws-secret
          mountPath: /root/.aws/
        - name: docker-config
          mountPath: /kaniko/.docker/
  restartPolicy: Never
  volumes:
    - name: aws-secret
      secret:
        secretName: aws-secret
    - name: docker-config
      configMap:
        name: docker-config
