---
apiVersion: mongodb.com/v1
kind: MongoDBMulti
metadata:
  name: multi-replica-set
spec:
  version: 4.4.0-ent
  type: ReplicaSet
  persistent: false
  credentials: my-credentials
  clusterSpecList:
    clusterSpecs:
      - clusterName: alpha
      - clusterName: bravo
