#!/usr/bin/env bash

set -Eeou pipefail

# Temporary development images built from mongot master
export MDB_SEARCH_COMMUNITY_VERSION="1.51.0-44-g33ee8acbe" # Sep 2nd mongot master
export MDB_SEARCH_COMMUNITY_NAME="mongot/community"
export MDB_SEARCH_COMMUNITY_REPO_URL="268558157000.dkr.ecr.eu-west-1.amazonaws.com"
