apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-ycsb-job
spec:
{{ if eq .Values.action "run" }}
  parallelism: {{ .Values.parallelism  }}
{{ else }}  
  parallelism: 1
{{ end }}
  template:
    metadata:
      name: {{ .Release.Name }}-ycsb-job
      namespace: {{ .Release.Namespace }}
    spec:
      restartPolicy: OnFailure
      volumes:
      - name: workload-volume
        configMap:
          name: {{ .Release.Name }}-workload
      containers:
      - name: ycsb-run
        image: jmimick/ycsb:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: workload-volume
          mountPath: /work
        env:
        - name: DB 
          value: {{ .Values.db }}
        - name: ACTION
          value: {{ .Values.action }}
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.binding }}
              key: username
              optional: true
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.binding }}
              key: password
              optional: true
        - name: URI
          valueFrom:
            secretKeyRef:
              name: {{ .Values.binding }}
              key: uri
