vars:
  quay_registry: quay.io/mongodb/mongodb-kubernetes-database
  s3_bucket: s3://enterprise-operator-dockerfiles/dockerfiles/mongodb-kubernetes-database

images:
- name: database
  vars:
    context: docker/mongodb-kubernetes-database
  platform: linux/amd64

  stages:
  - name: database-build-context
    task_type: docker_build
    dockerfile: Dockerfile.builder
    output:
    - registry: $(inputs.params.registry)/mongodb-enterprise-database-context
      tag: $(inputs.params.version_id)

  - name: init-appdb-template
    task_type: dockerfile_template
    inputs:
    - version
    output:
    - dockerfile: $(functions.tempfile)

  - name: database-build-ubi
    task_type: docker_build
    dockerfile: $(stages['init-appdb-template'].outputs[0].dockerfile)
    buildargs:
      imagebase: $(inputs.params.registry)/mongodb-enterprise-database-context:$(inputs.params.version_id)
    output:
    - registry: $(inputs.params.registry)/mongodb-kubernetes-database
      tag: $(inputs.params.version_id)

  - name: master-latest
    task_type: tag_image
    tags: ["master"]
    source:
      registry: $(inputs.params.registry)/mongodb-kubernetes-database
      tag: $(inputs.params.version_id)
    destination:
      - registry: $(inputs.params.registry)/mongodb-kubernetes-database
        tag: latest

  - name: database-release-context
    task_type: tag_image
    tags: ["release"]
    source:
      registry: $(inputs.params.registry)/mongodb-enterprise-database-context
      tag: $(inputs.params.version_id)
    destination:
    - registry: $(inputs.params.quay_registry)
      tag: $(inputs.params.version)-context

  - name: database-template
    task_type: dockerfile_template
    tags: ["release"]
    inputs:
    - version
    output:
    - dockerfile: $(inputs.params.s3_bucket)/$(inputs.params.version)/ubi/Dockerfile
