---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}

spec:
  type: {{ .Values.type | quote }}
  members: {{ .Values.members }}

  service: {{ .Release.Name }}
  # Using a version >= 4.0 will enable SCRAM-SHA-256 authentication
  # setting a version < 4.0 will enable SCRAM-SHA-1/MONGODB-CR authentication
  version: 4.0.4-ent

  opsManager:
    configMapRef:
{{- if .Values.opsManager.configMap }}
      name: {{ .Values.opsManager.configMap }}
{{- else }}
      name: {{ .Values.name }}-configmap
{{- end }}
{{- if .Values.opsManager.secretRef }}
  credentials: {{ .Values.opsManager.secretRef }}
{{- else }}
  credentials: {{ .Values.name }}-credential
{{- end }}

  security:
    authentication:
      enabled: true
      modes:
        {{- range .Values.security.authentication.modes }}
        - {{ . | quote }} # Valid authentication modes are "SCRAM' and "X509"
        {{- end }}
    {{- if .Values.security.tls.enabled }}
    tls:
      enabled: {{ .Values.security.tls.enabled }}
    {{- end }}
