---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-enterprise-database-pods
  {{- if not (eq (.Values.watchNamespace | default "*") "*") }}
  namespace: {{ .Values.watchNamespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
