name: ops-manager-kubernetes
description: An Ops Manager Kubernetes Operator
version: 0.1.0
kubeVersion: ">=1.9"
keywords:
  - mongodb
home: https://github.com/10gen/ops-manager-kubernetes
maintainers:
  - name: Ops Manager Team
    email: ops-manager-team@mongodb.com
