---
name: ops-manager
replicas: 1
version: "4.4.4"


# Kubernetes internal DNS
clusterName: cluster.local


# Ops Manager Global Admin user name and password.
# Ensure it complies with OpsManager password format
globalAdmin: "test@test.com"
globalAdminPassword: "KubeTest!1"
globalAdminFirstName: "First Name"
globalAdminLastName: "Last Name"

# enable Access Lists for Ops Manager
publicApi:
  whitelistEnabled: false


# Required: SMTP Mail server set up for password recovery
mail:
  adminEmailAddr: "support@example.com"
  hostname: "email-smtp.us-east-1.amazonaws.com"
  port: "465"
  ssl: "true"
  transport: "smtp"
