---
apiVersion: mongodb.com/v1beta1
kind: MongoDbShardedCluster
metadata:
  name: shannon
  namespace: mongodb
spec:
  shardCount: 2
  mongodsPerShardCount: 3
  mongos_count: 2
  config_server_count: 3
  mongodb_version: 3.6.3
  ops_manager_config: global-om-config
  persistent: false






