apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 3000
      protocol: TCP
  selector:
    app: grafana
