apiVersion: v1
kind: Service
metadata:
  name: prometheus-int
  namespace: monitoring
  labels:
    app: prometheus
    component: core
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 9090
      protocol: TCP
  selector:
    app: prometheus
    component: core
