## MongoDB Enterprise Database

# Set this to true if your cluster is managing SecurityContext for you.
# If running OpenShift (Cloud, Minishift, etc.), set this to true.
managedSecurityContext: false

# Section to describe components that needs to be installed
mongodb-enterprise-operator:
  enabled: true


# Optional configuration.
deployValidationWebhooks: true

name: mdbreplset
type: ReplicaSet
members: 3
opsManager:
  # Ops Manager connection need to be configured with Values and This HELM chart will create
  # necessary Secret and Config Map.
  URL:
  orgid:
  APIKey:
  APISecret:

security:
  authentication:
    modes: ["SCRAM"]  # Valid authentication modes are "SCRAM", "LDAP" and "X509"
  tls:
    enabled: true

clusterName: cluster.local

registry:
  pullPolicy: Always

users:
  - username: ycsb
    db: admin
    password: "ycsbpassword"
    roles:
      - db: admin
        name: readWriteAnyDatabase
  - username: admin-user
    db: admin
    password: "%SomeLong%password$foradmin"
    roles:
      - db: admin
        name: clusterAdmin
      - db: admin
        name: userAdminAnyDatabase
      - db: admin
        name: readWrite
      - db: admin
        name: userAdminAnyDatabase
